#!/bin/bash

    sed 's/   /　　/g' | \
    sed 's/\[ \] */☐ /g' | \
    sed 's/\[ *\* *\] /☑ /g' | \
    sed 's/\[ *\x *\] /☒ /g' | \
    sed 's/\[ *> *\] */▷ /g' | \
    sed 's/\[ *< *\] */◀ /g' | \
    cat 
