#!/bin/bash

    xsel -o -b | \
    sed 's/	/　/g' | \
    sed 's/\[ \] */☐ /g' | \
    sed 's/\[ *\* *\] /☑ /g' | \
    sed 's/\[ *\x *\] /☒ /g' | \
    sed 's/\[ *> *\] */▷ /g' | \
    sed 's/\[ *< *\] */◀ /g' | \
    sed 's/^\(\s*\)\*/\1•/g' | \
    xsel -i -b 
